export const AllLanguageFromJson = [
  { "Language": "English", "Native": "English", "BCP47": "en" },
  { "Language": "Afrikaans", "Native": "Afrikaans", "BCP47": "af" },
  { "Language": "Albanian", "Native": "gjuha shqipe [ɟ͡ʝuha", "BCP47": "sq" },
  { "Language": "Aymara", "Native": "	Aymar aru", "BCP47": "ay" },
  { "Language": "Azerbaijani", "Native": "آذربایجان دیلی", "BCP47": "az" },
  { "Language": "Bambara", "Native": "ߓߊߡߊߣߊ߲ߞߊ߲", "BCP47": "bm" },
  { "Language": "Basque", "Native": "euskara", "BCP47": "eu" },
  { "Language": "Bosnian", "Native": "بۉسانسقى", "BCP47": "bs" },
  { "Language": "Catalan", "Native": "català", "BCP47": "ca" },
  { "Language": "Cebuano", "Native": "Binisaya", "BCP47": "ceb" },
  { "Language": "Corsican", "Native": "corsu", "BCP47": "co" },
  { "Language": "Croatian", "Native": "[xř̩ʋaːtskiː]", "BCP47": "hr" },
  { "Language": "Czech", "Native": "	čeština / český jazyk", "BCP47": "cs" },
  { "Language": "Danish", "Native": "[ˈtænˀsk]", "BCP47": "da" },
  { "Language": "Dutch", "Native": "Nederlands", "BCP47": "nl-NL" },
  { "Language": "Esperanto", "Native": "espeˈranto", "BCP47": "eo" },
  { "Language": "Estonian", "Native": "ˈeːsti ˈkeːl", "BCP47": "et" },
  { "Language": "Ewe", "Native": "ɛβɛɡ͡bɛ", "BCP47": "ee" },
  { "Language": "Filipino (Tagalog)", "Native": "tɐˈɡaːloɡ", "BCP47": "fil" },
  { "Language": "Finnish", "Native": "suomi / suomen kieli", "BCP47": "fi" },
  { "Language": "French", "Native": "Français", "BCP47": "fr-FR" },
  { "Language": "Frisian", "Native": "Ōstfräisk", "BCP47": "fy" },
  { "Language": "Galician", "Native": "Galego", "BCP47": "gl" },
  { "Language": "German", "Native": "Deutsch", "BCP47": "de-DE" },
  { "Language": "Guarani", "Native": "avañeʼẽ [ʔãʋãɲẽˈʔẽ]", "BCP47": "gn" },
  { "Language": "Haitian Creole", "Native": "[kɣejɔl ajisjɛ̃]", "BCP47": "ht" },
  { "Language": "Hausa", "Native": "(Harshen Hausa) هَرْشَن هَوْسَ", "BCP47": "ha" },
  { "Language": "Hawaiian", "Native": "	ʻŌlelo Hawaiʻi [ʔoːˈlɛlo həˈvɐjʔi]", "BCP47": "haw" },
  { "Language": "Hmong", "Native": "lol Hmongb", "BCP47": "hmn" },
  { "Language": "Hungarian", "Native": "	magyar / magyar nyelv", "BCP47": "hu" },
  { "Language": "Icelandic", "Native": "Íslenska", "BCP47": "is" },
  { "Language": "Igbo", "Native": "	Ásụ̀sụ̀ Ìgbò", "BCP47": "ig" },
  { "Language": "Ilocano", "Native": "Iloco", "BCP47": "ilo" },
  { "Language": "Indonesian", "Native": "Bahasa Indonesia", "BCP47": "id-ID" },
  { "Language": "Irish", "Native": "	Gaeilge [ˈɡeːlʲɟə]", "BCP47": "ga" },
  { "Language": "Italian", "Native": "italiano", "BCP47": "it-IT" },
  { "Language": "Javanese", "Native": " ꦧꦱꦗꦮ / باسا جاوا [bɔsɔ d͡ʒɔwɔ]", "BCP47": "jv" },
  { "Language": "Kinyarwanda", "Native": "Ikinyarwanda", "BCP47": "rw" },
  { "Language": "Krio", "Native": "Krio", "BCP47": "kri" },
  { "Language": "Kurdish", "Native": "(Kurdî) کوردی", "BCP47": "ku" },
  { "Language": "Latin", "Native": "	Lingua Latina", "BCP47": "la" },
  { "Language": "Latvian", "Native": "	latviešu valoda", "BCP47": "lv" },
  { "Language": "Lingala", "Native": "Lingála", "BCP47": "ln" },
  { "Language": "Lithuanian", "Native": "lietuvių kalba", "BCP47": "lt" },
  { "Language": "Luganda", "Native": "Oluganda", "BCP47": "lg" },
  { "Language": "Luxembourgish", "Native": "	Lëtzebuergesch [ˈlətsəbuəjəʃ]", "BCP47": "lb" },
  { "Language": "Malagasy", "Native": "fiteny malagasy", "BCP47": "mg" },
  { "Language": "Malay", "Native": "بهاس ملايو", "BCP47": "ms" },
  { "Language": "Maltese", "Native": "	Malti [mɐlti̞:]", "BCP47": "mt" },
  { "Language": "Maori", "Native": "Māori ", "BCP47": "mi" },
  { "Language": "Mizo", "Native": "	Mizo ṭawng", "BCP47": "lus" },
  { "Language": "Norwegian", "Native": "Norsk", "BCP47": "no-NO" },
  { "Language": "Oromo", "Native": "Oromiff", "BCP47": "om" },
  { "Language": "Polish", "Native": "polski", "BCP47": "pl" },
  { "Language": "Portuguese", "Native": "Português", "BCP47": "pt-PT" },
  { "Language": "Quechua", "Native": "Kechua", "BCP47": "qu" },
  { "Language": "Romanian", "Native": "limba română / român", "BCP47": "ro-RO" },
  { "Language": "Samoan", "Native": "Gagana fa‘a Sāmoa", "BCP47": "sm" },
  { "Language": "Scots Gaelic", "Native": "Scots", "BCP47": "gd" },
  { "Language": "Sepedi", "Native": "	Sesotho sa Leboa", "BCP47": "nso" },
  { "Language": "Sesotho", "Native": "seSotho", "BCP47": "st" },
  { "Language": "Shona", "Native": "chiShona", "BCP47": "sn" },
  { "Language": "Slovak", "Native": "slovenčina", "BCP47": "sk" },
  { "Language": "Slovenian", "Native": "[slɔˈʋèːnʃtʃina]", "BCP47": "sl" },
  { "Language": "Somali", "Native": "	af Soomaali (اَف صَومالي˜)", "BCP47": "so" },
  { "Language": "Spanish", "Native": "Español", "BCP47": "es-ES" },
  { "Language": "Sundanese", "Native": "	Basa Sunda", "BCP47": "su" },
  { "Language": "Swahili", "Native": "کِسْوَهِيلِ", "BCP47": "sw" },
  { "Language": "Swedish", "Native": "Svenska", "BCP47": "sv-SE" },
  { "Language": "Tagalog (Filipino)", "Native": "[tɐˈɡaːloɡ]", "BCP47": "tl" },
  { "Language": "Tsonga", "Native": "Xitsonga", "BCP47": "ts" },
  { "Language": "Turkish", "Native": "Türkçe", "BCP47": "tr" },
  { "Language": "Turkmen", "Native": " تۆرکمن ديلی", "BCP47": "tk" },
  { "Language": "Twi (Akan)", "Native": "Twi", "BCP47": "ak" },
  { "Language": "Uzbek", "Native": "Ўзбек тили", "BCP47": "uz" },
  { "Language": "Vietnamese", "Native": "㗂越", "BCP47": "vi" },
  { "Language": "Welsh", "Native": "[kəmˈrai̯ɡ / kəmˈraːɡ / kʊmˈraːɡ]", "BCP47": "cy" },
  { "Language": "Xhosa", "Native": "[isiˈǁʰɔsa]", "BCP47": "xh" },
  { "Language": "Yoruba", "Native": "Èdè Yorùbá [e˩de˩ joru˩ba˥]", "BCP47": "yo" },
  { "Language": "Zulu", "Native": "DeutisiZulusch", "BCP47": "zu" },
  { "Language": "Belarusian", "Native": "Беларуская мова", "BCP47": "be" },
  { "Language": "Bulgarian", "Native": "Български", "BCP47": "bg" },
  { "Language": "Kazakh", "Native": "قازاقشا / قازاق تىلى", "BCP47": "kk" },
  { "Language": "Macedonian", "Native": "македонски (makedonski)", "BCP47": "mk" },
  { "Language": "Mongolian", "Native": "[ˈmɔɴɢɔ̆ɮ çiɮ]", "BCP47": "mn" },
  { "Language": "Russian", "Native": "Русский", "BCP47": "ru-RU" },
  { "Language": "Serbian", "Native": "српски (srpski) српски језик (srpski jezik)", "BCP47": "sr-SP" },
  { "Language": "Tatar", "Native": "تاتارچا", "BCP47": "tt" },
  { "Language": "Ukrainian", "Native": "українська мова ", "BCP47": "uk" },
  { "Language": "Konkani", "Native": "कोंकणी", "BCP47": "gom" },
  { "Language": "Maithili", "Native": "Macushi", "BCP47": "mai" },
  { "Language": "Marathi", "Native": "मराठी ", "BCP47": "mr" },
  { "Language": "Nyanja (Chichewa)", "Native": "	Chicheŵa [ʧiʧeβa]", "BCP47": "ny" },
  { "Language": "Sanskrit", "Native": "संस्कृतम् ", "BCP47": "sa" },
  { "Language": "Dogri", "Native": "ڈوگرى", "BCP47": "doi" },
  { "Language": "Hindi", "Native": "हिन्दी ", "BCP47": "hi" },
  { "Language": "Nepali", "Native": "नेपाली ", "BCP47": "ne" },  
  { "Language": "Pashto", "Native": "پښتو", "BCP47": "ps" },
  { "Language": "Persian", "Native": "[fɒːɾˈsiː] (fārsi) فارسی", "BCP47": "fa" },
  { "Language": "Urdu", "Native": "اُردُو", "BCP47": "ur" },
  { "Language": "Arabic", "Native": "العربية", "BCP47": "ar-SA" },
  { "Language": "Uyghur", "Native": "ئۇيغۇرچە", "BCP47": "ug" },
  { "Language": "Assamese", "Native": "অসমীয়া ", "BCP47": "as" },
  { "Language": "Bengali", "Native": "বাংলা", "BCP47": "bn-BD" },
  { "Language": "Kyrgyz", "Native": "قىرعىز تىلى", "BCP47": "ky" },
  { "Language": "Tajik", "Native": "	тоҷикӣ (tojikī) تجيكى [tɔdʒiˈki])", "BCP47": "tg" },
  { "Language": "Hebrew", "Native": "(ivrit) עברית / עִבְרִית", "BCP47": "he" },
  { "Language": "Yiddish", "Native": "[ˈ(j)ɪdɪʃ] (yidish) ייִדי", "BCP47": "yi" },
  { "Language": "Armenian", "Native": "arevelahayeren", "BCP47": "hy" },
  { "Language": "Myanmar (Burmese)", "Native": "[mjəmà zəɡá]", "BCP47": "my" },
  { "Language": "Amharic", "Native": "ኣማርኛ (Amarəñña)", "BCP47": "am" },
  { "Language": "Tigrinya", "Native": "ትግርኛ ", "BCP47": "ti" },  
  { "Language": "Georgian", "Native": "	ქართული ენა", "BCP47": "ka" },
  { "Language": "Greek", "Native": "	ελληνικά (ellēniká)", "BCP47": "el-GR" },
  { "Language": "Punjabi", "Native": "پنجابی", "BCP47": "pa" },
  { "Language": "Mandarin Chinese", "Native": "普通话", "BCP47": "zh-CN" },
  { "Language": "Korean", "Native": "한국어 [韓國語] (han-guk-eo)", "BCP47": "ko" },
  { "Language": "Japanese", "Native": "日本語 (nihongo)", "BCP47": "ja" },
  { "Language": "Bhojpuri", "Native": "भोजपुरी", "BCP47": "bho" },
  { "Language": "Kannada", "Native": "ಕನ್ನಡ", "BCP47": "kn" },
  { "Language": "Khmer", "Native": "ភាសាខ្មែរ (phéasa khmê) [pʰiəˈsaː kʰmae]", "BCP47": "km" },
  { "Language": "Kurdish (Sorani)", "Native": "سۆرانی", "BCP47": "ckb" },
  { "Language": "Lao", "Native": "ລາວ ", "BCP47": "lo" },
  { "Language": "Malayalam", "Native": "മലയാളം ", "BCP47": "ml" },
  { "Language": "Odia (Oriya)", "Native": "	ଓଡ଼ିଆ (oṛiā) [oˈɽiaː]", "BCP47": "or" },
  { "Language": "Sindhi", "Native": "سنڌي", "BCP47": "sd" },
  { "Language": "Sinhala (Sinhalese)", "Native": "සිංහල ", "BCP47": "si" },
  { "Language": "Gujarati", "Native": "ગુજરાતી", "BCP47": "gu" },
  { "Language": "Tamil", "Native": "தமிழ் ", "BCP47": "ta" },
  { "Language": "Telugu", "Native": "తెలుగు ", "BCP47": "te" },
  { "Language": "Dhivehi", "Native": "d̪iˈʋehi", "BCP47": "dv" },
  { "Language": "Thai", "Native": "ภาษาไทย", "BCP47": "th" },
]

export const MickSupportedLanguage =[ "en","en-US" , "zh-CN" , "es-ES" , "ar-SA" , "ru-RU" , "bn-BD" , "pt-PT" , "id-ID" , "fr-FR" , "af" , "eu" , "ca" , "ar-SA" , "cs" , "nl-NL" , "fi" , "gl" , "de-DE" , "el-GR" , "he" , "hu" , "is" , "it-IT" , "ja" , "ko" , "la" , "no-NO" , "pl" , "ro-RO" , "sr-SP" , "sk" , "sv-SE" , "tr" , "zu" 
]






















